export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";

export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";

export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE"

export const UPDATE_PRODUCT_STATUS = 'UPDATE_PRODUCT_STATUS';

export const ADD_ITEM = "ADD_ITEM";